### PR TITLE
Python 3 compatibility done

### PR DESCRIPTION
**Pull request by timkofu**
Tests are now passing for Python 2 and Python 3 ( tested with Python 2.7.11 and Python 3.5.1 )

### CODE REVIEW

**Comment by timkofu** [comment]
Opening a new pull requests with current master deployed in production and working well.

**Comment by timkofu** [comment]
Current master is deployed in production and works with both Python 2 and Python 3.

**Comment by kelonye** [comment]
Thank you sir! Sorry for the late checkin.

**Comment by kelonye** [comment]
Published new version to pypi

**Pull request merged**
